#pragma once
#define MAX_LINE_LENGTH 1024

#define MAX_SOUND_CHANNELS 8
#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 640

#define PLAYER_SPEED 150

#define RENDER_SCALE_X 2
#define RENDER_SCALE_Y 2

#define SCALED_SCREEN_WIDTH (SCREEN_WIDTH / RENDER_SCALE_X)
#define SCALED_SCREEN_HEIGHT (SCREEN_HEIGHT / RENDER_SCALE_Y)

#define WRAP_AROUND_DISTANCE 50

#ifndef GAME_NAME
#define GAME_NAME "Add Game Name to CMakeLists.txt"
#endif